"""Initial migration.

Revision ID: 9ea55259f4fb
Revises: 
Create Date: 2022-08-23 20:49:49.328990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea55259f4fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pi_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi_subscription_to_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi_subscription_to_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(length=4), nullable=False),
    sa.Column('pretty_name', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(length=16), nullable=False),
    sa.Column('pretty_name', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_name')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bot_token', sa.String(length=64), nullable=False),
    sa.Column('bot_user_id', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('subscriber')
    op.drop_table('pi_vendor')
    op.drop_table('pi_type')
    op.drop_table('pi_subscription_to_vendor')
    op.drop_table('pi_subscription_to_type')
    op.drop_table('pi_subscription')
    # ### end Alembic commands ###
